app:
  # app run port
  port: 8000
  pprof_port: 8090
  app_env: "local"
  app_debug: true
  app_name: "news"
  graceful_wait: 5s

# db config
db:
  user: "m_syscfaas_dy"
  password: "O19cDYjcO76V1J^Ww!zi"
  host: "syscaptainfaas.mysql.db.lpt.qa.nt.ctripcorp.com"
  port: "55444"
  dbname: "syscaptainfaasdb"
